[package]
name = "sfs"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13.0"
fernet = "0.2.0"
rpassword = "7.0.0"
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
serde = "1.0.145"
serde_derive = "1.0.145"
sha2 = "0.10.6"
toml = "0.5.9"
whoami = "1.2.3"
