prompt = "$BOLD$$BLUE$$sfs::path$ >$NORMAL$ "
debug_mode = false

[list_command]
display_all_files = false
list_view = false
grid_columns = 7
decrypt_name = false
file_format = "$sfs::name$"
folder_format = "$BLUE$$sfs::name$"
decrypted_format = "$YELLOW$$sfs::decrypted_name$ $BOLD$($sfs::name$)"

[encrypt_command]
recursive = false
silent = false
overwrite = false
keep_file = false
hashing_algorithm = "xxh3"
chunk_size = 1048576
assign_random_name = false
progress_bar_format = "$BOLD$$sfs::file.name$:$NORMAL$ [{elapsed_precise}] [{wide_bar:.blue/white}] {bytes}/{total_bytes} ({eta})"

[decrypt_command]
recursive = false
silent = false
overwrite = false
keep_file = false
use_original_name = false
no_verify_chunks = false
progress_bar_format = "$BOLD$$sfs::file.name$:$NORMAL$ [{elapsed_precise}] [{wide_bar:.blue/white}] {bytes}/{total_bytes} ({eta})"
